- repo: local

  hooks:
  - id: pylint
    name: Pylint
    entry: pipenv run pylint "src/*"
    language: system
    types: [python]
    stages: [commit]
  - id: black
    name: Black
    entry: pipenv run black --check src
    language: python
    types: [python]
    stages: [commit]
  - id: mypy
    name: MyPy
    entry: pipenv run mypy src
    language: python
    types: [python]
    stages: [commit]
  - id: unit
    name: Unit tests
    entry: pipenv run pytest -m unit
    language: python
    types: [python]
    stages: [push]
    always_run: true
  - id: security
    name: Security
    entry: pipenv check
    language: python
    types: [python]
    stages: [push]
    always_run: true
